trigger: none

pr:
  branches:
    include:
    - "*"

#variables:
  # - template: ../variables.yml
  # - name: dockerfilesFolder
  #   value: $(Build.SourcesDirectory)/eng/docker
  # - name: httpStressProject
  #   value: $(sourcesRoot)/System.Net.Http/tests/StressTests/HttpStress
  # - name: sdkBaseImage
  #   value: dotnet-sdk-libraries-current

extends:
  template:  /eng/pipelines/common/templates/pipeline-with-resources.yml
  parameters:
    stages:
    - stage: Build
      jobs:
      - job: windows
        displayName: Test
        timeoutInMinutes: 150
        pool:
          name: $(DncEngPublicBuildPool)
          demands: ImageOverride -equals 1es-windows-2022-open

        steps:
        - checkout: self
          clean: true
          fetchDepth: 5
          lfs: false

        - powershell: |
            & "$(Build.SourcesDirectory)/build.cmd" clr+libs -ci -rc Release -c Release
          name: buildRuntime
          displayName: Build CLR and Libraries